services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./logs:/app/logs
    networks:
      - imfgx_network
    depends_on:
      - redis
      - rabbitmq
      - postgres

  postgres:
    image: postgres:14.15-alpine3.21
    env_file:
      - .env
    volumes:
      - imfgx-postgres:/var/lib/postgresql/data
    networks:
      - imfgx_network

  redis:
    image: redis:7.2.7-alpine3.21
    volumes:
      - imfgx-redis:/data
    networks:
      - imfgx_network
  rabbitmq:
    image: rabbitmq:management-alpine
    volumes:
      - imfgx-rabbitmq:/var/lib/rabbitmq
    networks:
      - imfgx_network
    ports:
      - 15672:15672

volumes:
  imfgx_logs:
  imfgx-redis:
  imfgx-rabbitmq:
  imfgx-postgres:

networks:
  imfgx_network:
